// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCrawlerApp.Infra.Data.Contexts;

#nullable disable

namespace WebCrawlerApp.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251018125416_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebCrawlerApp.Domain.Entities.CrawlerPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CrawlerRunId")
                        .HasColumnType("int");

                    b.Property<string>("HtmlFilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<int>("RowsExtracted")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CrawlerRunId");

                    b.ToTable("CrawlerPages", (string)null);
                });

            modelBuilder.Entity("WebCrawlerApp.Domain.Entities.CrawlerRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("JsonFilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("PagesProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalRowsExtracted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("CrawlerRuns", (string)null);
                });

            modelBuilder.Entity("WebCrawlerApp.Domain.Entities.ProxyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("CrawlerRunId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CrawlerRunId");

                    b.HasIndex("IpAddress", "Port", "Protocol")
                        .HasDatabaseName("IX_Proxy_Unique");

                    b.ToTable("ProxyRecords", (string)null);
                });

            modelBuilder.Entity("WebCrawlerApp.Domain.Entities.CrawlerPage", b =>
                {
                    b.HasOne("WebCrawlerApp.Domain.Entities.CrawlerRun", "CrawlerRun")
                        .WithMany("Pages")
                        .HasForeignKey("CrawlerRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrawlerRun");
                });

            modelBuilder.Entity("WebCrawlerApp.Domain.Entities.ProxyRecord", b =>
                {
                    b.HasOne("WebCrawlerApp.Domain.Entities.CrawlerRun", "CrawlerRun")
                        .WithMany("Records")
                        .HasForeignKey("CrawlerRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrawlerRun");
                });

            modelBuilder.Entity("WebCrawlerApp.Domain.Entities.CrawlerRun", b =>
                {
                    b.Navigation("Pages");

                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
